// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetMeResponse = {
    /**
     * Unique identifier for the user
     */
    id: number;
    /**
     * Full name of the user
     */
    name: string;
    /**
     * Email address of the user
     */
    email: string;
    role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
};

export type GetSshKeyData = {
    /**
     * Unique identifier for the SSH key
     */
    id: number;
    /**
     * Name of the SSH key
     */
    name: string;
    /**
     * Public key string
     */
    publicKey: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type GetSshKeyResponse = {
    /**
     * List of SSH keys
     */
    values: Array<{
        /**
         * Unique identifier for the SSH key
         */
        id: number;
        /**
         * Name of the SSH key
         */
        name: string;
        /**
         * Public key string
         */
        publicKey: string;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type GetSshKeyRequestQuery = {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
};

export type AddSshKeyRequestBody = {
    /**
     * Name of the SSH key
     */
    name: string;
    /**
     * Public key string
     */
    publicKey: string;
};

export type AddSshKeyResponse = {
    /**
     * Unique identifier for the SSH key
     */
    id: number;
    /**
     * Name of the SSH key
     */
    name: string;
    /**
     * Public key string
     */
    publicKey: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type RemoveSshKeyRequestBody = {
    /**
     * Unique identifiers for the SSH keys to be removed
     */
    keyIds: Array<number>;
};

export type GetInstancesRequestQuery = {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    /**
     * Filter instances by course ID
     */
    courseId?: number;
    /**
     * Filter instances by semester ID
     */
    semesterId?: number;
};

export type GetInstancesResponse = {
    /**
     * List of instances
     */
    values: Array<{
        /**
         * Unique identifier for the instance
         */
        id: number;
        /**
         * Details of the course offering associated with the instance
         */
        courseOffering?: {
            /**
             * Course code associated with the offering
             */
            courseCode: string;
            /**
             * Title of the course
             */
            courseTitle: string;
            /**
             * Semester in which the course is offered
             */
            semester: string;
        };
        status: 'PENDING' | 'ACTIVE' | 'PROMOTED' | 'INACTIVE' | 'DELETED';
        /**
         * Details about the virtual machine hosting the instance if available
         */
        vmDetails?: {
            /**
             * Hostname of the virtual machine
             */
            hostname: string;
            /**
             * Operating system installed on the virtual machine
             */
            os: string;
            /**
             * IP address of the virtual machine
             */
            ip: string;
            /**
             * Number of CPUs allocated to the virtual machine
             */
            cpus: number;
            /**
             * Amount of memory (in MB) allocated to the virtual machine
             */
            memoryMB: number;
            /**
             * Disk size (in GB) of the virtual machine
             */
            diskGB: number;
        };
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type GetInstanceRequestParams = {
    /**
     * Unique identifier for the instance
     */
    instanceId: number;
};

export type GetInstanceResponse = {
    /**
     * Unique identifier for the instance
     */
    id: number;
    /**
     * Details of the course offering associated with the instance
     */
    courseOffering?: {
        /**
         * Course code associated with the offering
         */
        courseCode: string;
        /**
         * Title of the course
         */
        courseTitle: string;
        /**
         * Semester in which the course is offered
         */
        semester: string;
    };
    status: 'PENDING' | 'ACTIVE' | 'PROMOTED' | 'INACTIVE' | 'DELETED';
    /**
     * Details about the virtual machine hosting the instance if available
     */
    vmDetails?: {
        /**
         * Hostname of the virtual machine
         */
        hostname: string;
        /**
         * Operating system installed on the virtual machine
         */
        os: string;
        /**
         * IP address of the virtual machine
         */
        ip: string;
        /**
         * Number of CPUs allocated to the virtual machine
         */
        cpus: number;
        /**
         * Amount of memory (in MB) allocated to the virtual machine
         */
        memoryMB: number;
        /**
         * Disk size (in GB) of the virtual machine
         */
        diskGB: number;
    };
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
    /**
     * List of reverse proxy configurations associated with the instance
     */
    reverseProxy: Array<{
        /**
         * Unique identifier for the reverse proxy configuration
         */
        id: number;
        /**
         * Target port on the instance
         */
        targetPort: number;
    }>;
};

export type CreateInstanceRequestBody = {
    /**
     * Unique identifier for the PVE template to be used
     */
    pveTemplateId: number;
    /**
     * Unique identifier for the course offering associated with the instance
     */
    courseOfferingId?: number;
    /**
     * Number of CPUs to allocate to the instance
     */
    cpus: number;
    /**
     * Amount of memory (in MB) to allocate to the instance
     */
    memoryMB: number;
    /**
     * Disk size (in GB) to allocate to the instance
     */
    diskGB: number;
};

export type CreateInstanceResponse = {
    /**
     * Unique identifier for the newly created instance
     */
    id: number;
    /**
     * Details of the course offering associated with the instance
     */
    courseOffering?: {
        /**
         * Course code associated with the offering
         */
        courseCode: string;
        /**
         * Title of the course
         */
        courseTitle: string;
        /**
         * Semester in which the course is offered
         */
        semester: string;
    };
    status: 'PENDING' | 'ACTIVE' | 'PROMOTED' | 'INACTIVE' | 'DELETED';
    /**
     * Details about the virtual machine hosting the instance if available
     */
    vmDetails?: {
        /**
         * Hostname of the virtual machine
         */
        hostname: string;
        /**
         * Operating system installed on the virtual machine
         */
        os: string;
        /**
         * IP address of the virtual machine
         */
        ip: string;
        /**
         * Number of CPUs allocated to the virtual machine
         */
        cpus: number;
        /**
         * Amount of memory (in MB) allocated to the virtual machine
         */
        memoryMB: number;
        /**
         * Disk size (in GB) of the virtual machine
         */
        diskGB: number;
    };
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type DeleteInstanceRequestParams = {
    /**
     * Unique identifier for the instance to be deleted
     */
    instanceId: number;
};

export type DeleteInstanceResponse = {
    /**
     * Indicates whether the deletion was successful
     */
    success: boolean;
};

export type CreateReverseProxyRequestBody = {
    /**
     * Target port on the instance
     */
    targetPort: number;
    type: 'HTTPS' | 'HTTP';
    /**
     * Description of the reverse proxy
     */
    description?: string;
};

/**
 * Reverse proxy configuration
 */
export type CreateReverseProxyResponse = {
    /**
     * Unique identifier for the reverse proxy
     */
    id: number;
    /**
     * Target port on the instance
     */
    targetPort: number;
    type: 'HTTPS' | 'HTTP';
    /**
     * Description of the reverse proxy
     */
    description?: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * List of reverse proxy configurations
 */
export type GetReverseProxiesResponse = Array<{
    /**
     * Unique identifier for the reverse proxy
     */
    id: number;
    /**
     * Target port on the instance
     */
    targetPort: number;
    type: 'HTTPS' | 'HTTP';
    /**
     * Description of the reverse proxy
     */
    description?: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
}>;

export type DeleteReverseProxyRequestParams = {
    /**
     * Unique identifier for the instance
     */
    instanceId: number;
    /**
     * Unique identifier for the reverse proxy to delete
     */
    proxyId: number;
};

export type DeleteReverseProxyResponse = {
    /**
     * Indicates whether the deletion was successful
     */
    success: boolean;
};

export type PromoteInstanceRequestParams = {
    /**
     * Unique identifier for the instance to promote
     */
    instanceId: number;
};

export type PromoteInstanceResponse = {
    /**
     * Unique identifier for the promoted instance
     */
    id: number;
    status: 'PENDING' | 'ACTIVE' | 'PROMOTED' | 'INACTIVE' | 'DELETED';
    /**
     * Success message
     */
    message: string;
};

export type GetInstanceAuditLogsResponse = {
    /**
     * List of audit log entries
     */
    values: Array<{
        /**
         * Unique identifier for the audit log entry
         */
        id: number;
        /**
         * Action performed on the instance
         */
        action: string;
        performedBy: {
            /**
             * Platform user ID
             */
            id: number;
            /**
             * User name
             */
            name: string;
            /**
             * User email
             */
            email: string;
        };
        /**
         * When the action was performed
         */
        timestamp: unknown | string | number;
        /**
         * Additional notes about the action
         */
        notes?: string;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

/**
 * Represents an entry in the instructor mailing list
 */
export type InstructorMailingListValue = {
    /**
     * Unique identifier for the mailing list value
     */
    id: number;
    /**
     * Email address of the instructor
     */
    email: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Represents an entry in the instructor listing
 */
export type InstructorValue = {
    /**
     * Unique identifier for the instructor listing
     */
    id: number;
    /**
     * Full name of the instructor
     */
    name: string;
    /**
     * Email address of the instructor
     */
    email: string;
    role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Represents a course offered in the academic system
 */
export type CourseValue = {
    /**
     * Unique identifier for the course
     */
    id: number;
    /**
     * Course code
     */
    code: string;
    /**
     * Title of the course
     */
    title: string;
    /**
     * Description of the course
     */
    description?: string;
    /**
     * Indicates if the course is currently active
     */
    isActive: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Represents a semester in the academic system
 */
export type SemesterValue = {
    /**
     * Unique identifier for the semester
     */
    id: number;
    /**
     * Name of the semester
     */
    name: string;
    /**
     * Start date of the semester
     */
    startDate: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate: unknown | string | number;
    /**
     * Indicates if this semester is the current active semester
     */
    isCurrent: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Query parameters for fetching instructor mailing list
 */
export type GetInstructorMailingListQuery = {
    /**
     * Filter by email address with partial match
     */
    email?: string;
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
};

/**
 * Response structure for instructor mailing list
 */
export type GetInstructorMailingListResponse = {
    /**
     * List of instructor mailing list entries
     */
    values: Array<{
        /**
         * Unique identifier for the mailing list value
         */
        id: number;
        /**
         * Email address of the instructor
         */
        email: string;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

/**
 * Request parameters for fetching instructor mailing list by ID
 */
export type InstructorMailingListByIdRequestParams = {
    /**
     * Unique identifier for the mailing list entry
     */
    mailingId: number;
};

/**
 * Request body for adding an instructor to the mailing list
 */
export type AddInstructorMailingListRequestBody = {
    /**
     * Email address of the instructor
     */
    email: string;
};

/**
 * Response structure after adding an instructor to the mailing list
 */
export type AddInstructorMailingListResponse = {
    /**
     * Unique identifier for the mailing list value
     */
    id: number;
    /**
     * Email address of the instructor
     */
    email: string;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Response structure after removing an instructor from the mailing list
 */
export type RemoveInstructorMailingListResponse = {
    /**
     * Indicates if the removal was successful
     */
    success: boolean;
};

/**
 * Query parameters for fetching instructor listing
 */
export type GetInstructorsRequestQuery = {
    /**
     * Filter by instructor name with partial match
     */
    name?: string;
    /**
     * Filter by email address with partial match
     */
    email?: string;
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
};

/**
 * Response structure for instructor listing
 */
export type GetInstructorsResponse = {
    /**
     * List of instructors
     */
    values: Array<{
        /**
         * Unique identifier for the instructor listing
         */
        id: number;
        /**
         * Full name of the instructor
         */
        name: string;
        /**
         * Email address of the instructor
         */
        email: string;
        role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

/**
 * Request parameters for fetching instructor by ID
 */
export type InstructorByIdRequestParams = {
    /**
     * Unique identifier for the instructor
     */
    instructorId: number;
};

/**
 * Response structure for fetching instructor by ID
 */
export type GetInstructorByIdResponse = {
    /**
     * Unique identifier for the instructor listing
     */
    id: number;
    /**
     * Full name of the instructor
     */
    name: string;
    /**
     * Email address of the instructor
     */
    email: string;
    role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
    /**
     * List of courses taught by the instructor
     */
    courses: Array<{
        /**
         * Unique identifier for the course
         */
        id: number;
        /**
         * Course code
         */
        code: string;
        /**
         * Title of the course
         */
        title: string;
        /**
         * Description of the course
         */
        description?: string;
        /**
         * Indicates if the course is currently active
         */
        isActive: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Request body for editing instructor details
 */
export type EditInstructorByIdRequestBody = {
    role?: 'ADMIN' | 'INSTRUCTOR';
    /**
     * List of course IDs to be associated with the instructor
     */
    courseIds?: Array<number>;
};

/**
 * Response structure after editing instructor details
 */
export type EditInstructorByIdResponse = {
    /**
     * Unique identifier for the instructor listing
     */
    id: number;
    /**
     * Full name of the instructor
     */
    name: string;
    /**
     * Email address of the instructor
     */
    email: string;
    role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
    /**
     * List of courses taught by the instructor
     */
    courses: Array<{
        /**
         * Unique identifier for the course
         */
        id: number;
        /**
         * Course code
         */
        code: string;
        /**
         * Title of the course
         */
        title: string;
        /**
         * Description of the course
         */
        description?: string;
        /**
         * Indicates if the course is currently active
         */
        isActive: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Response structure after deleting an instructor by ID
 */
export type DeleteInstructorByIdResponse = {
    /**
     * Indicates if the deletion was successful
     */
    success: boolean;
};

/**
 * Query parameters for fetching course listing
 */
export type GetCoursesRequestQuery = {
    /**
     * Filter by course code with partial match
     */
    code?: string;
    /**
     * Filter by course title with partial match
     */
    title?: string;
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
};

/**
 * Response structure for course listing
 */
export type GetCoursesResponse = {
    /**
     * List of courses
     */
    values: Array<{
        /**
         * Unique identifier for the course
         */
        id: number;
        /**
         * Course code
         */
        code: string;
        /**
         * Title of the course
         */
        title: string;
        /**
         * Description of the course
         */
        description?: string;
        /**
         * Indicates if the course is currently active
         */
        isActive: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

/**
 * Request parameters for fetching course by ID
 */
export type CourseByIdRequestParams = {
    /**
     * Unique identifier for the course
     */
    courseId: number;
};

/**
 * Response structure for fetching course by ID
 */
export type GetCourseByIdResponse = {
    /**
     * Unique identifier for the course
     */
    id: number;
    /**
     * Course code
     */
    code: string;
    /**
     * Title of the course
     */
    title: string;
    /**
     * Description of the course
     */
    description?: string;
    /**
     * Indicates if the course is currently active
     */
    isActive: boolean;
    /**
     * List of instructors teaching the course
     */
    instructors: Array<{
        /**
         * Unique identifier for the instructor listing
         */
        id: number;
        /**
         * Full name of the instructor
         */
        name: string;
        /**
         * Email address of the instructor
         */
        email: string;
        role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * List of semesters when the course is offered
     */
    semesters: Array<{
        /**
         * Unique identifier for the semester
         */
        id: number;
        /**
         * Name of the semester
         */
        name: string;
        /**
         * Start date of the semester
         */
        startDate: unknown | string | number;
        /**
         * End date of the semester
         */
        endDate: unknown | string | number;
        /**
         * Indicates if this semester is the current active semester
         */
        isCurrent: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Request body for adding a new course
 */
export type AddCourseRequestBody = {
    /**
     * Course code
     */
    code: string;
    /**
     * Title of the course
     */
    title: string;
    /**
     * Description of the course
     */
    description?: string;
};

/**
 * Response structure after adding a new course
 */
export type AddCourseResponse = {
    /**
     * Unique identifier for the course
     */
    id: number;
    /**
     * Course code
     */
    code: string;
    /**
     * Title of the course
     */
    title: string;
    /**
     * Description of the course
     */
    description?: string;
    /**
     * Indicates if the course is currently active
     */
    isActive: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Request body for editing course details
 */
export type EditCourseByIdRequestBody = {
    /**
     * Course code
     */
    code?: string;
    /**
     * Title of the course
     */
    title?: string;
    /**
     * Description of the course
     */
    description?: string;
    /**
     * Indicates if the course is currently active
     */
    isActive?: boolean;
};

/**
 * Request body for associating an instructor with a course
 */
export type EditCourseInstructorRequestBody = {
    /**
     * List of instructor IDs to be associated with the course
     */
    instructorIds: Array<number>;
};

/**
 * Response structure after associating an instructor with a course
 */
export type EditCourseInstructorResponse = {
    /**
     * List of instructors associated with the course
     */
    instructors: Array<{
        /**
         * Unique identifier for the instructor listing
         */
        id: number;
        /**
         * Full name of the instructor
         */
        name: string;
        /**
         * Email address of the instructor
         */
        email: string;
        role: 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Request body for associating a semester with a course
 */
export type EditCourseSemesterRequestBody = {
    /**
     * List of semester IDs to be associated with the course
     */
    semesterIds: Array<number>;
};

/**
 * Response structure after associating a semester with a course
 */
export type EditCourseSemesterResponse = {
    /**
     * List of semesters associated with the course
     */
    semesters: Array<{
        /**
         * Unique identifier for the semester
         */
        id: number;
        /**
         * Name of the semester
         */
        name: string;
        /**
         * Start date of the semester
         */
        startDate: unknown | string | number;
        /**
         * End date of the semester
         */
        endDate: unknown | string | number;
        /**
         * Indicates if this semester is the current active semester
         */
        isCurrent: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Query parameters for fetching semester listing
 */
export type GetSemestersRequestQuery = {
    /**
     * Filter by semester name with partial match
     */
    name?: string;
    /**
     * Filter semesters starting from this date
     */
    dateFrom?: unknown | string | number;
    /**
     * Filter semesters ending by this date
     */
    dateTo?: unknown | string | number;
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
};

/**
 * Response structure for semester listing
 */
export type GetSemestersResponse = {
    /**
     * List of semesters
     */
    values: Array<{
        /**
         * Unique identifier for the semester
         */
        id: number;
        /**
         * Name of the semester
         */
        name: string;
        /**
         * Start date of the semester
         */
        startDate: unknown | string | number;
        /**
         * End date of the semester
         */
        endDate: unknown | string | number;
        /**
         * Indicates if this semester is the current active semester
         */
        isCurrent: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

/**
 * Request parameters for fetching semester by ID
 */
export type SemesterByIdRequestParams = {
    /**
     * Unique identifier for the semester
     */
    semesterId: number;
};

/**
 * Response structure for fetching semester by ID
 */
export type GetSemesterByIdResponse = {
    /**
     * Unique identifier for the semester
     */
    id: number;
    /**
     * Name of the semester
     */
    name: string;
    /**
     * Start date of the semester
     */
    startDate: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate: unknown | string | number;
    /**
     * Indicates if this semester is the current active semester
     */
    isCurrent: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
    /**
     * List of courses offered in the semester
     */
    courses: Array<{
        /**
         * Unique identifier for the course
         */
        id: number;
        /**
         * Course code
         */
        code: string;
        /**
         * Title of the course
         */
        title: string;
        /**
         * Description of the course
         */
        description?: string;
        /**
         * Indicates if the course is currently active
         */
        isActive: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Request body for adding a new semester
 */
export type AddSemesterRequestBody = {
    /**
     * Name of the semester
     */
    name: string;
    /**
     * Start date of the semester
     */
    startDate: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate: unknown | string | number;
};

/**
 * Response structure after adding a new semester
 */
export type AddSemesterResponse = {
    /**
     * Unique identifier for the semester
     */
    id: number;
    /**
     * Name of the semester
     */
    name: string;
    /**
     * Start date of the semester
     */
    startDate: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate: unknown | string | number;
    /**
     * Indicates if this semester is the current active semester
     */
    isCurrent: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Request body for editing semester details
 */
export type EditSemesterByIdRequestBody = {
    /**
     * Name of the semester
     */
    name?: string;
    /**
     * Start date of the semester
     */
    startDate?: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate?: unknown | string | number;
    /**
     * Indicates if this semester is the current active semester
     */
    isCurrent?: boolean;
};

/**
 * Response structure after editing semester details
 */
export type EditSemesterByIdResponse = {
    /**
     * Unique identifier for the semester
     */
    id: number;
    /**
     * Name of the semester
     */
    name: string;
    /**
     * Start date of the semester
     */
    startDate: unknown | string | number;
    /**
     * End date of the semester
     */
    endDate: unknown | string | number;
    /**
     * Indicates if this semester is the current active semester
     */
    isCurrent: boolean;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Request body for associating a course with a semester
 */
export type EditSemesterCourseRequestBody = {
    /**
     * List of course IDs to be associated with the semester
     */
    courseIds: Array<number>;
};

/**
 * Response structure after associating a course with a semester
 */
export type EditSemesterCourseResponse = {
    /**
     * List of courses associated with the semester
     */
    courses: Array<{
        /**
         * Unique identifier for the course
         */
        id: number;
        /**
         * Course code
         */
        code: string;
        /**
         * Title of the course
         */
        title: string;
        /**
         * Description of the course
         */
        description?: string;
        /**
         * Indicates if the course is currently active
         */
        isActive: boolean;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
};

/**
 * Response structure after deleting a semester by ID
 */
export type DeleteSemesterByIdResponse = {
    /**
     * Indicates if the deletion was successful
     */
    success: boolean;
};

export type ApprovalStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';

/**
 * Request data
 */
export type RequestItem = {
    /**
     * Request ID
     */
    id: number;
    /**
     * Request title
     */
    title: string;
    /**
     * Request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    specs: {
        /**
         * Number of CPUs requested
         */
        cpus: number;
        /**
         * Memory requested in MB
         */
        memoryMB: number;
        /**
         * Disk size requested in GB
         */
        diskGB: number;
    };
    /**
     * Chosen template name
     */
    templateName?: string;
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

/**
 * Extended request data
 */
export type ExtendedRequestItem = {
    /**
     * Extended request ID
     */
    id: number;
    /**
     * Extended request title
     */
    title: string;
    /**
     * Extended request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Target instance ID
     */
    targetInstanceId: number;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    /**
     * Summary of a semester
     */
    nextSemester?: {
        /**
         * Semester ID
         */
        id: number;
        /**
         * Semester name
         */
        name: string;
        /**
         * Semester start date
         */
        startDate: unknown | string | number;
        /**
         * Semester end date
         */
        endDate: unknown | string | number;
    };
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type CreateRequestRequestBody = {
    /**
     * Request title
     */
    title: string;
    /**
     * Request description
     */
    description?: string;
    /**
     * Course offering ID
     */
    courseOfferingId: number;
    /**
     * Template ID
     */
    pveTemplateId: number;
    /**
     * Number of CPUs requested
     */
    cpus: number;
    /**
     * Memory requested in MB
     */
    memoryMB: number;
    /**
     * Disk size requested in GB
     */
    diskGB: number;
};

/**
 * Request data
 */
export type CreateRequestResponse = {
    /**
     * Request ID
     */
    id: number;
    /**
     * Request title
     */
    title: string;
    /**
     * Request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    specs: {
        /**
         * Number of CPUs requested
         */
        cpus: number;
        /**
         * Memory requested in MB
         */
        memoryMB: number;
        /**
         * Disk size requested in GB
         */
        diskGB: number;
    };
    /**
     * Chosen template name
     */
    templateName?: string;
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type GetRequestsRequestQuery = {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Filter by course ID
     */
    courseId?: number;
    /**
     * Filter by semester ID
     */
    semesterId?: number;
};

export type GetRequestsResponse = {
    values: Array<{
        /**
         * Request ID
         */
        id: number;
        /**
         * Request title
         */
        title: string;
        /**
         * Request description
         */
        description?: string;
        status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        /**
         * Reviewer or requester note
         */
        reason?: string;
        /**
         * Summary of a course offering
         */
        courseOffering?: {
            /**
             * Course code
             */
            courseCode: string;
            /**
             * Course title
             */
            courseTitle: string;
            /**
             * Semester name
             */
            semester: string;
        };
        specs: {
            /**
             * Number of CPUs requested
             */
            cpus: number;
            /**
             * Memory requested in MB
             */
            memoryMB: number;
            /**
             * Disk size requested in GB
             */
            diskGB: number;
        };
        /**
         * Chosen template name
         */
        templateName?: string;
        /**
         * Requester platform user ID
         */
        requesterId: number;
        /**
         * Reviewer platform user ID
         */
        reviewerId?: number;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type UpdateRequestStatusRequestBody = {
    status: 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reason for the action
     */
    reason?: string;
};

/**
 * Request data
 */
export type UpdateRequestStatusResponse = {
    /**
     * Request ID
     */
    id: number;
    /**
     * Request title
     */
    title: string;
    /**
     * Request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    specs: {
        /**
         * Number of CPUs requested
         */
        cpus: number;
        /**
         * Memory requested in MB
         */
        memoryMB: number;
        /**
         * Disk size requested in GB
         */
        diskGB: number;
    };
    /**
     * Chosen template name
     */
    templateName?: string;
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type CreateExtendedRequestRequestBody = {
    /**
     * Extended request title
     */
    title: string;
    /**
     * Extended request description
     */
    description?: string;
    /**
     * Instance to be extended
     */
    targetInstanceId: number;
};

/**
 * Extended request data
 */
export type CreateExtendedRequestResponse = {
    /**
     * Extended request ID
     */
    id: number;
    /**
     * Extended request title
     */
    title: string;
    /**
     * Extended request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Target instance ID
     */
    targetInstanceId: number;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    /**
     * Summary of a semester
     */
    nextSemester?: {
        /**
         * Semester ID
         */
        id: number;
        /**
         * Semester name
         */
        name: string;
        /**
         * Semester start date
         */
        startDate: unknown | string | number;
        /**
         * Semester end date
         */
        endDate: unknown | string | number;
    };
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type GetExtendedRequestsRequestQuery = {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Filter by course ID
     */
    courseId?: number;
    /**
     * Filter by semester ID
     */
    semesterId?: number;
    /**
     * Filter by instance ID
     */
    instanceId?: number;
};

export type GetExtendedRequestsResponse = {
    values: Array<{
        /**
         * Extended request ID
         */
        id: number;
        /**
         * Extended request title
         */
        title: string;
        /**
         * Extended request description
         */
        description?: string;
        status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        /**
         * Reviewer or requester note
         */
        reason?: string;
        /**
         * Target instance ID
         */
        targetInstanceId: number;
        /**
         * Summary of a course offering
         */
        courseOffering?: {
            /**
             * Course code
             */
            courseCode: string;
            /**
             * Course title
             */
            courseTitle: string;
            /**
             * Semester name
             */
            semester: string;
        };
        /**
         * Summary of a semester
         */
        nextSemester?: {
            /**
             * Semester ID
             */
            id: number;
            /**
             * Semester name
             */
            name: string;
            /**
             * Semester start date
             */
            startDate: unknown | string | number;
            /**
             * Semester end date
             */
            endDate: unknown | string | number;
        };
        /**
         * Requester platform user ID
         */
        requesterId: number;
        /**
         * Reviewer platform user ID
         */
        reviewerId?: number;
        /**
         * Timestamp when the record was created
         */
        createdAt?: unknown | string | number;
        /**
         * Timestamp when the record was last updated
         */
        updatedAt?: unknown | string | number;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type UpdateExtendedRequestStatusRequestBody = {
    status: 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reason for the action
     */
    reason?: string;
};

/**
 * Extended request data
 */
export type UpdateExtendedRequestStatusResponse = {
    /**
     * Extended request ID
     */
    id: number;
    /**
     * Extended request title
     */
    title: string;
    /**
     * Extended request description
     */
    description?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
    /**
     * Reviewer or requester note
     */
    reason?: string;
    /**
     * Target instance ID
     */
    targetInstanceId: number;
    /**
     * Summary of a course offering
     */
    courseOffering?: {
        /**
         * Course code
         */
        courseCode: string;
        /**
         * Course title
         */
        courseTitle: string;
        /**
         * Semester name
         */
        semester: string;
    };
    /**
     * Summary of a semester
     */
    nextSemester?: {
        /**
         * Semester ID
         */
        id: number;
        /**
         * Semester name
         */
        name: string;
        /**
         * Semester start date
         */
        startDate: unknown | string | number;
        /**
         * Semester end date
         */
        endDate: unknown | string | number;
    };
    /**
     * Requester platform user ID
     */
    requesterId: number;
    /**
     * Reviewer platform user ID
     */
    reviewerId?: number;
    /**
     * Timestamp when the record was created
     */
    createdAt?: unknown | string | number;
    /**
     * Timestamp when the record was last updated
     */
    updatedAt?: unknown | string | number;
};

export type GetRequestAuditLogsResponse = {
    /**
     * List of request audit log entries
     */
    values: Array<{
        /**
         * Audit log entry ID
         */
        id: number;
        action: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        performedBy: {
            /**
             * Platform user ID
             */
            id: number;
            /**
             * User name
             */
            name: string;
            /**
             * User email
             */
            email: string;
        };
        /**
         * When the action was performed
         */
        timestamp: unknown | string | number;
        /**
         * Additional notes about the action
         */
        notes?: string;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type GetExtendedRequestAuditLogsResponse = {
    /**
     * List of extended request audit log entries
     */
    values: Array<{
        /**
         * Audit log entry ID
         */
        id: number;
        action: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        performedBy: {
            /**
             * Platform user ID
             */
            id: number;
            /**
             * User name
             */
            name: string;
            /**
             * User email
             */
            email: string;
        };
        /**
         * When the action was performed
         */
        timestamp: unknown | string | number;
        /**
         * Additional notes about the action
         */
        notes?: string;
    }>;
    /**
     * Total number of items available
     */
    totalItems: number;
    /**
     * Total number of pages available
     */
    totalPages: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeResponses = {
    /**
     * Response for status 200
     */
    200: GetMeResponse;
};

export type GetApiUserMeResponse = GetApiUserMeResponses[keyof GetApiUserMeResponses];

export type DeleteApiUserSshKeysData = {
    body: RemoveSshKeyRequestBody;
    path?: never;
    query?: never;
    url: '/api/user/ssh-keys';
};

export type DeleteApiUserSshKeysResponses = {
    /**
     * Number of SSH keys removed
     */
    200: number;
};

export type DeleteApiUserSshKeysResponse = DeleteApiUserSshKeysResponses[keyof DeleteApiUserSshKeysResponses];

export type GetApiUserSshKeysData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/api/user/ssh-keys';
};

export type GetApiUserSshKeysResponses = {
    /**
     * Response for status 200
     */
    200: GetSshKeyResponse;
};

export type GetApiUserSshKeysResponse = GetApiUserSshKeysResponses[keyof GetApiUserSshKeysResponses];

export type PostApiUserSshKeysData = {
    body: AddSshKeyRequestBody;
    path?: never;
    query?: never;
    url: '/api/user/ssh-keys';
};

export type PostApiUserSshKeysResponses = {
    /**
     * Response for status 200
     */
    200: AddSshKeyResponse;
};

export type PostApiUserSshKeysResponse = PostApiUserSshKeysResponses[keyof PostApiUserSshKeysResponses];

export type GetApiInstancesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Filter instances by course ID
         */
        courseId?: number;
        /**
         * Filter instances by semester ID
         */
        semesterId?: number;
    };
    url: '/api/instances/';
};

export type GetApiInstancesResponses = {
    /**
     * Response for status 200
     */
    200: GetInstancesResponse;
};

export type GetApiInstancesResponse = GetApiInstancesResponses[keyof GetApiInstancesResponses];

export type PostApiInstancesData = {
    body: CreateInstanceRequestBody;
    path?: never;
    query?: never;
    url: '/api/instances/';
};

export type PostApiInstancesErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type PostApiInstancesError = PostApiInstancesErrors[keyof PostApiInstancesErrors];

export type PostApiInstancesResponses = {
    /**
     * Response for status 200
     */
    200: CreateInstanceResponse;
};

export type PostApiInstancesResponse = PostApiInstancesResponses[keyof PostApiInstancesResponses];

export type GetApiInstancesAdminData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Filter instances by course ID
         */
        courseId?: number;
        /**
         * Filter instances by semester ID
         */
        semesterId?: number;
    };
    url: '/api/instances/admin';
};

export type GetApiInstancesAdminResponses = {
    /**
     * Response for status 200
     */
    200: GetInstancesResponse;
};

export type GetApiInstancesAdminResponse = GetApiInstancesAdminResponses[keyof GetApiInstancesAdminResponses];

export type GetApiInstancesInstructorData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Filter instances by course ID
         */
        courseId?: number;
        /**
         * Filter instances by semester ID
         */
        semesterId?: number;
    };
    url: '/api/instances/instructor';
};

export type GetApiInstancesInstructorErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type GetApiInstancesInstructorError = GetApiInstancesInstructorErrors[keyof GetApiInstancesInstructorErrors];

export type GetApiInstancesInstructorResponses = {
    /**
     * Response for status 200
     */
    200: GetInstancesResponse;
};

export type GetApiInstancesInstructorResponse = GetApiInstancesInstructorResponses[keyof GetApiInstancesInstructorResponses];

export type DeleteApiInstancesByInstanceIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance to be deleted
         */
        instanceId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}';
};

export type DeleteApiInstancesByInstanceIdResponses = {
    /**
     * Response for status 200
     */
    200: DeleteInstanceResponse;
};

export type DeleteApiInstancesByInstanceIdResponse = DeleteApiInstancesByInstanceIdResponses[keyof DeleteApiInstancesByInstanceIdResponses];

export type GetApiInstancesByInstanceIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance
         */
        instanceId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}';
};

export type GetApiInstancesByInstanceIdResponses = {
    /**
     * Response for status 200
     */
    200: GetInstanceResponse;
};

export type GetApiInstancesByInstanceIdResponse = GetApiInstancesByInstanceIdResponses[keyof GetApiInstancesByInstanceIdResponses];

export type GetApiInstancesByInstanceIdReverseProxiesData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance
         */
        instanceId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}/reverse-proxies';
};

export type GetApiInstancesByInstanceIdReverseProxiesResponses = {
    /**
     * List of reverse proxy configurations
     */
    200: GetReverseProxiesResponse;
};

export type GetApiInstancesByInstanceIdReverseProxiesResponse = GetApiInstancesByInstanceIdReverseProxiesResponses[keyof GetApiInstancesByInstanceIdReverseProxiesResponses];

export type PostApiInstancesByInstanceIdReverseProxiesData = {
    body: CreateReverseProxyRequestBody;
    path: {
        /**
         * Unique identifier for the instance
         */
        instanceId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}/reverse-proxies';
};

export type PostApiInstancesByInstanceIdReverseProxiesResponses = {
    /**
     * Reverse proxy configuration
     */
    200: CreateReverseProxyResponse;
};

export type PostApiInstancesByInstanceIdReverseProxiesResponse = PostApiInstancesByInstanceIdReverseProxiesResponses[keyof PostApiInstancesByInstanceIdReverseProxiesResponses];

export type DeleteApiInstancesByInstanceIdReverseProxiesByProxyIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance
         */
        instanceId: number;
        /**
         * Unique identifier for the reverse proxy to delete
         */
        proxyId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}/reverse-proxies/{proxyId}';
};

export type DeleteApiInstancesByInstanceIdReverseProxiesByProxyIdResponses = {
    /**
     * Response for status 200
     */
    200: DeleteReverseProxyResponse;
};

export type DeleteApiInstancesByInstanceIdReverseProxiesByProxyIdResponse = DeleteApiInstancesByInstanceIdReverseProxiesByProxyIdResponses[keyof DeleteApiInstancesByInstanceIdReverseProxiesByProxyIdResponses];

export type PatchApiInstancesByInstanceIdPromoteData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance to promote
         */
        instanceId: number;
    };
    query?: never;
    url: '/api/instances/{instanceId}/promote';
};

export type PatchApiInstancesByInstanceIdPromoteErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type PatchApiInstancesByInstanceIdPromoteError = PatchApiInstancesByInstanceIdPromoteErrors[keyof PatchApiInstancesByInstanceIdPromoteErrors];

export type PatchApiInstancesByInstanceIdPromoteResponses = {
    /**
     * Response for status 200
     */
    200: PromoteInstanceResponse;
};

export type PatchApiInstancesByInstanceIdPromoteResponse = PatchApiInstancesByInstanceIdPromoteResponses[keyof PatchApiInstancesByInstanceIdPromoteResponses];

export type GetApiInstancesByInstanceIdAuditLogsData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instance
         */
        instanceId: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/instances/{instanceId}/audit-logs';
};

export type GetApiInstancesByInstanceIdAuditLogsErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type GetApiInstancesByInstanceIdAuditLogsError = GetApiInstancesByInstanceIdAuditLogsErrors[keyof GetApiInstancesByInstanceIdAuditLogsErrors];

export type GetApiInstancesByInstanceIdAuditLogsResponses = {
    /**
     * Response for status 200
     */
    200: GetInstanceAuditLogsResponse;
};

export type GetApiInstancesByInstanceIdAuditLogsResponse = GetApiInstancesByInstanceIdAuditLogsResponses[keyof GetApiInstancesByInstanceIdAuditLogsResponses];

export type GetApiAcademicMailingListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by email address with partial match
         */
        email?: string;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/api/academic/mailing-list';
};

export type GetApiAcademicMailingListResponses = {
    /**
     * Response structure for instructor mailing list
     */
    200: GetInstructorMailingListResponse;
};

export type GetApiAcademicMailingListResponse = GetApiAcademicMailingListResponses[keyof GetApiAcademicMailingListResponses];

export type PostApiAcademicMailingListData = {
    /**
     * Request body for adding an instructor to the mailing list
     */
    body: AddInstructorMailingListRequestBody;
    path?: never;
    query?: never;
    url: '/api/academic/mailing-list';
};

export type PostApiAcademicMailingListResponses = {
    /**
     * Response structure after adding an instructor to the mailing list
     */
    200: AddInstructorMailingListResponse;
};

export type PostApiAcademicMailingListResponse = PostApiAcademicMailingListResponses[keyof PostApiAcademicMailingListResponses];

export type DeleteApiAcademicMailingListByMailingIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the mailing list entry
         */
        mailingId: number;
    };
    query?: never;
    url: '/api/academic/mailing-list/{mailingId}';
};

export type DeleteApiAcademicMailingListByMailingIdResponses = {
    /**
     * Response structure after removing an instructor from the mailing list
     */
    200: RemoveInstructorMailingListResponse;
};

export type DeleteApiAcademicMailingListByMailingIdResponse = DeleteApiAcademicMailingListByMailingIdResponses[keyof DeleteApiAcademicMailingListByMailingIdResponses];

export type GetApiAcademicInstructorsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by instructor name with partial match
         */
        name?: string;
        /**
         * Filter by email address with partial match
         */
        email?: string;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/api/academic/instructors';
};

export type GetApiAcademicInstructorsResponses = {
    /**
     * Response structure for instructor listing
     */
    200: GetInstructorsResponse;
};

export type GetApiAcademicInstructorsResponse = GetApiAcademicInstructorsResponses[keyof GetApiAcademicInstructorsResponses];

export type GetApiAcademicInstructorsByInstructorIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the instructor
         */
        instructorId: number;
    };
    query?: never;
    url: '/api/academic/instructors/{instructorId}';
};

export type GetApiAcademicInstructorsByInstructorIdResponses = {
    /**
     * Response structure for fetching instructor by ID
     */
    200: GetInstructorByIdResponse;
};

export type GetApiAcademicInstructorsByInstructorIdResponse = GetApiAcademicInstructorsByInstructorIdResponses[keyof GetApiAcademicInstructorsByInstructorIdResponses];

export type PatchApiAcademicInstructorsByInstructorIdData = {
    /**
     * Request body for editing instructor details
     */
    body: EditInstructorByIdRequestBody;
    path: {
        /**
         * Unique identifier for the instructor
         */
        instructorId: number;
    };
    query?: never;
    url: '/api/academic/instructors/{instructorId}';
};

export type PatchApiAcademicInstructorsByInstructorIdResponses = {
    /**
     * Response structure after editing instructor details
     */
    200: EditInstructorByIdResponse;
};

export type PatchApiAcademicInstructorsByInstructorIdResponse = PatchApiAcademicInstructorsByInstructorIdResponses[keyof PatchApiAcademicInstructorsByInstructorIdResponses];

export type GetApiAcademicCoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by course code with partial match
         */
        code?: string;
        /**
         * Filter by course title with partial match
         */
        title?: string;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/api/academic/courses';
};

export type GetApiAcademicCoursesResponses = {
    /**
     * Response structure for course listing
     */
    200: GetCoursesResponse;
};

export type GetApiAcademicCoursesResponse = GetApiAcademicCoursesResponses[keyof GetApiAcademicCoursesResponses];

export type PostApiAcademicCoursesData = {
    /**
     * Request body for adding a new course
     */
    body: AddCourseRequestBody;
    path?: never;
    query?: never;
    url: '/api/academic/courses';
};

export type PostApiAcademicCoursesResponses = {
    /**
     * Response structure after adding a new course
     */
    200: AddCourseResponse;
};

export type PostApiAcademicCoursesResponse = PostApiAcademicCoursesResponses[keyof PostApiAcademicCoursesResponses];

export type GetApiAcademicCoursesByCourseIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the course
         */
        courseId: number;
    };
    query?: never;
    url: '/api/academic/courses/{courseId}';
};

export type GetApiAcademicCoursesByCourseIdResponses = {
    /**
     * Response structure for fetching course by ID
     */
    200: GetCourseByIdResponse;
};

export type GetApiAcademicCoursesByCourseIdResponse = GetApiAcademicCoursesByCourseIdResponses[keyof GetApiAcademicCoursesByCourseIdResponses];

export type PatchApiAcademicCoursesByCourseIdData = {
    /**
     * Request body for editing course details
     */
    body: EditCourseByIdRequestBody;
    path: {
        /**
         * Unique identifier for the course
         */
        courseId: number;
    };
    query?: never;
    url: '/api/academic/courses/{courseId}';
};

export type PatchApiAcademicCoursesByCourseIdResponses = {
    /**
     * Response structure after adding a new course
     */
    200: AddCourseResponse;
};

export type PatchApiAcademicCoursesByCourseIdResponse = PatchApiAcademicCoursesByCourseIdResponses[keyof PatchApiAcademicCoursesByCourseIdResponses];

export type PatchApiAcademicCoursesByCourseIdInstructorsData = {
    /**
     * Request body for associating an instructor with a course
     */
    body: EditCourseInstructorRequestBody;
    path: {
        /**
         * Unique identifier for the course
         */
        courseId: number;
    };
    query?: never;
    url: '/api/academic/courses/{courseId}/instructors';
};

export type PatchApiAcademicCoursesByCourseIdInstructorsResponses = {
    /**
     * Response structure after associating an instructor with a course
     */
    200: EditCourseInstructorResponse;
};

export type PatchApiAcademicCoursesByCourseIdInstructorsResponse = PatchApiAcademicCoursesByCourseIdInstructorsResponses[keyof PatchApiAcademicCoursesByCourseIdInstructorsResponses];

export type PatchApiAcademicCoursesByCourseIdSemestersData = {
    /**
     * Request body for associating a semester with a course
     */
    body: EditCourseSemesterRequestBody;
    path: {
        /**
         * Unique identifier for the course
         */
        courseId: number;
    };
    query?: never;
    url: '/api/academic/courses/{courseId}/semesters';
};

export type PatchApiAcademicCoursesByCourseIdSemestersResponses = {
    /**
     * Response structure after associating a semester with a course
     */
    200: EditCourseSemesterResponse;
};

export type PatchApiAcademicCoursesByCourseIdSemestersResponse = PatchApiAcademicCoursesByCourseIdSemestersResponses[keyof PatchApiAcademicCoursesByCourseIdSemestersResponses];

export type GetApiAcademicSemestersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by semester name with partial match
         */
        name?: string;
        /**
         * Filter semesters starting from this date
         */
        dateFrom?: unknown | string | number;
        /**
         * Filter semesters ending by this date
         */
        dateTo?: unknown | string | number;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/api/academic/semesters';
};

export type GetApiAcademicSemestersResponses = {
    /**
     * Response structure for semester listing
     */
    200: GetSemestersResponse;
};

export type GetApiAcademicSemestersResponse = GetApiAcademicSemestersResponses[keyof GetApiAcademicSemestersResponses];

export type PostApiAcademicSemestersData = {
    /**
     * Request body for adding a new semester
     */
    body: AddSemesterRequestBody;
    path?: never;
    query?: never;
    url: '/api/academic/semesters';
};

export type PostApiAcademicSemestersResponses = {
    /**
     * Response structure after adding a new semester
     */
    200: AddSemesterResponse;
};

export type PostApiAcademicSemestersResponse = PostApiAcademicSemestersResponses[keyof PostApiAcademicSemestersResponses];

export type DeleteApiAcademicSemestersBySemesterIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the semester
         */
        semesterId: number;
    };
    query?: never;
    url: '/api/academic/semesters/{semesterId}';
};

export type DeleteApiAcademicSemestersBySemesterIdResponses = {
    /**
     * Response structure after deleting a semester by ID
     */
    200: DeleteSemesterByIdResponse;
};

export type DeleteApiAcademicSemestersBySemesterIdResponse = DeleteApiAcademicSemestersBySemesterIdResponses[keyof DeleteApiAcademicSemestersBySemesterIdResponses];

export type GetApiAcademicSemestersBySemesterIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the semester
         */
        semesterId: number;
    };
    query?: never;
    url: '/api/academic/semesters/{semesterId}';
};

export type GetApiAcademicSemestersBySemesterIdResponses = {
    /**
     * Response structure for fetching semester by ID
     */
    200: GetSemesterByIdResponse;
};

export type GetApiAcademicSemestersBySemesterIdResponse = GetApiAcademicSemestersBySemesterIdResponses[keyof GetApiAcademicSemestersBySemesterIdResponses];

export type PatchApiAcademicSemestersBySemesterIdData = {
    /**
     * Request body for editing semester details
     */
    body: EditSemesterByIdRequestBody;
    path: {
        /**
         * Unique identifier for the semester
         */
        semesterId: number;
    };
    query?: never;
    url: '/api/academic/semesters/{semesterId}';
};

export type PatchApiAcademicSemestersBySemesterIdResponses = {
    /**
     * Response structure after editing semester details
     */
    200: EditSemesterByIdResponse;
};

export type PatchApiAcademicSemestersBySemesterIdResponse = PatchApiAcademicSemestersBySemesterIdResponses[keyof PatchApiAcademicSemestersBySemesterIdResponses];

export type PatchApiAcademicSemestersBySemesterIdCoursesData = {
    /**
     * Request body for associating a course with a semester
     */
    body: EditSemesterCourseRequestBody;
    path: {
        /**
         * Unique identifier for the semester
         */
        semesterId: number;
    };
    query?: never;
    url: '/api/academic/semesters/{semesterId}/courses';
};

export type PatchApiAcademicSemestersBySemesterIdCoursesResponses = {
    /**
     * Response structure after associating a course with a semester
     */
    200: EditSemesterCourseResponse;
};

export type PatchApiAcademicSemestersBySemesterIdCoursesResponse = PatchApiAcademicSemestersBySemesterIdCoursesResponses[keyof PatchApiAcademicSemestersBySemesterIdCoursesResponses];

export type GetApiRequestsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        /**
         * Filter by course ID
         */
        courseId?: number;
        /**
         * Filter by semester ID
         */
        semesterId?: number;
    };
    url: '/api/requests/';
};

export type GetApiRequestsResponses = {
    /**
     * Response for status 200
     */
    200: GetRequestsResponse;
};

export type GetApiRequestsResponse = GetApiRequestsResponses[keyof GetApiRequestsResponses];

export type PostApiRequestsData = {
    body: CreateRequestRequestBody;
    path?: never;
    query?: never;
    url: '/api/requests/';
};

export type PostApiRequestsErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type PostApiRequestsError = PostApiRequestsErrors[keyof PostApiRequestsErrors];

export type PostApiRequestsResponses = {
    /**
     * Request data
     */
    200: CreateRequestResponse;
};

export type PostApiRequestsResponse = PostApiRequestsResponses[keyof PostApiRequestsResponses];

export type PatchApiRequestsByRequestIdStatusData = {
    body: UpdateRequestStatusRequestBody;
    path: {
        /**
         * Request ID
         */
        requestId: number;
    };
    query?: never;
    url: '/api/requests/{requestId}/status';
};

export type PatchApiRequestsByRequestIdStatusResponses = {
    /**
     * Request data
     */
    200: UpdateRequestStatusResponse;
};

export type PatchApiRequestsByRequestIdStatusResponse = PatchApiRequestsByRequestIdStatusResponses[keyof PatchApiRequestsByRequestIdStatusResponses];

export type GetApiRequestsByRequestIdAuditLogsData = {
    body?: never;
    path: {
        /**
         * Request ID
         */
        requestId: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/requests/{requestId}/audit-logs';
};

export type GetApiRequestsByRequestIdAuditLogsResponses = {
    /**
     * Response for status 200
     */
    200: GetRequestAuditLogsResponse;
};

export type GetApiRequestsByRequestIdAuditLogsResponse = GetApiRequestsByRequestIdAuditLogsResponses[keyof GetApiRequestsByRequestIdAuditLogsResponses];

export type GetApiExtendedRequestsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
        /**
         * Filter by course ID
         */
        courseId?: number;
        /**
         * Filter by semester ID
         */
        semesterId?: number;
        /**
         * Filter by instance ID
         */
        instanceId?: number;
    };
    url: '/api/extended-requests/';
};

export type GetApiExtendedRequestsResponses = {
    /**
     * Response for status 200
     */
    200: GetExtendedRequestsResponse;
};

export type GetApiExtendedRequestsResponse = GetApiExtendedRequestsResponses[keyof GetApiExtendedRequestsResponses];

export type PostApiExtendedRequestsData = {
    body: CreateExtendedRequestRequestBody;
    path?: never;
    query?: never;
    url: '/api/extended-requests/';
};

export type PostApiExtendedRequestsErrors = {
    /**
     * Response for status 403
     */
    403: {
        /**
         * HTTP status code
         */
        status: number;
        /**
         * Error message
         */
        message: string;
    };
};

export type PostApiExtendedRequestsError = PostApiExtendedRequestsErrors[keyof PostApiExtendedRequestsErrors];

export type PostApiExtendedRequestsResponses = {
    /**
     * Extended request data
     */
    200: CreateExtendedRequestResponse;
};

export type PostApiExtendedRequestsResponse = PostApiExtendedRequestsResponses[keyof PostApiExtendedRequestsResponses];

export type PatchApiExtendedRequestsByExtendedRequestIdStatusData = {
    body: UpdateExtendedRequestStatusRequestBody;
    path: {
        /**
         * Extended request ID
         */
        extendedRequestId: number;
    };
    query?: never;
    url: '/api/extended-requests/{extendedRequestId}/status';
};

export type PatchApiExtendedRequestsByExtendedRequestIdStatusResponses = {
    /**
     * Extended request data
     */
    200: UpdateExtendedRequestStatusResponse;
};

export type PatchApiExtendedRequestsByExtendedRequestIdStatusResponse = PatchApiExtendedRequestsByExtendedRequestIdStatusResponses[keyof PatchApiExtendedRequestsByExtendedRequestIdStatusResponses];

export type GetApiExtendedRequestsByExtendedRequestIdAuditLogsData = {
    body?: never;
    path: {
        /**
         * Extended request ID
         */
        extendedRequestId: number;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/extended-requests/{extendedRequestId}/audit-logs';
};

export type GetApiExtendedRequestsByExtendedRequestIdAuditLogsResponses = {
    /**
     * Response for status 200
     */
    200: GetExtendedRequestAuditLogsResponse;
};

export type GetApiExtendedRequestsByExtendedRequestIdAuditLogsResponse = GetApiExtendedRequestsByExtendedRequestIdAuditLogsResponses[keyof GetApiExtendedRequestsByExtendedRequestIdAuditLogsResponses];
