import type { Metadata } from "next";

import { UserProvider } from "@midori/contexts/user";

import SideNavbar from "@midori/components/navbar/Side";
import TopNavbar from "@midori/components/navbar/Top";

import User from "@midori/components/warper/User";
import { SidebarProvider } from "@midori/contexts/sidebar";

export const metadata: Metadata = {
  title: "FITM Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <UserProvider>
      <User>
        <SidebarProvider>
          <SideNavbar />

          <div className="flex-1 px-2 lg:pl-0 pb-2 flex flex-col">
            <TopNavbar />
            <div className="flex-1 p-2 bg-gray-100 rounded-lg overflow-y-auto">
              {children}
            </div>
          </div>
        </SidebarProvider>
      </User>
    </UserProvider>
  );
}
